-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 14:36:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_acesso` (
  `idAcesso` INT NOT NULL AUTO_INCREMENT,
  `acesso` INT(2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAcesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `hash` VARCHAR(60) NOT NULL,
  `FK_idAcesso` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_tbl_login_tbl_acesso1_idx` (`FK_idAcesso` ASC) VISIBLE,
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_login_tbl_acesso1`
    FOREIGN KEY (`FK_idAcesso`)
    REFERENCES `mydb`.`tbl_acesso` (`idAcesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` INT(15) NOT NULL,
  `whatsapp` VARCHAR(15) NOT NULL,
  `FK_idLogin` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_tbl_usuario_tbl_login1_idx` (`FK_idLogin` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_usuario_tbl_login1`
    FOREIGN KEY (`FK_idLogin`)
    REFERENCES `mydb`.`tbl_login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_CadLivro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_CadLivro` (
  `idCadLivro` INT NOT NULL AUTO_INCREMENT,
  `nomeLivro` VARCHAR(45) NOT NULL,
  `quantidadeDisp` INT NOT NULL,
  `condicao` VARCHAR(45) NOT NULL,
  `codigoLivro` INT NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCadLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `FK_idEmprestimo` INT NOT NULL,
  `FK_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idStatus`),
  INDEX `fk_tbl_status_tbl_emprestimo1_idx` (`FK_idEmprestimo` ASC) VISIBLE,
  INDEX `fk_tbl_status_tbl_usuario1_idx` (`FK_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_status_tbl_emprestimo1`
    FOREIGN KEY (`FK_idEmprestimo`)
    REFERENCES `mydb`.`tbl_emprestimo` (`idEmprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_status_tbl_usuario1`
    FOREIGN KEY (`FK_idUsuario`)
    REFERENCES `mydb`.`tbl_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_emprestimo` (
  `idEmprestimo` INT NOT NULL AUTO_INCREMENT,
  `dataRetirada` DATE NOT NULL,
  `dataEntrega` DATE NOT NULL,
  `FK_idUsuario` INT NOT NULL,
  `FK_idCadLivro` INT NOT NULL,
  `FK_idStatus` INT NOT NULL,
  PRIMARY KEY (`idEmprestimo`),
  INDEX `fk_tbl_emprestimo_tbl_usuario1_idx` (`FK_idUsuario` ASC) VISIBLE,
  INDEX `fk_tbl_emprestimo_tbl_CadLivro1_idx` (`FK_idCadLivro` ASC) VISIBLE,
  INDEX `fk_tbl_emprestimo_tbl_status1_idx` (`FK_idStatus` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_emprestimo_tbl_usuario1`
    FOREIGN KEY (`FK_idUsuario`)
    REFERENCES `mydb`.`tbl_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_emprestimo_tbl_CadLivro1`
    FOREIGN KEY (`FK_idCadLivro`)
    REFERENCES `mydb`.`tbl_CadLivro` (`idCadLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_emprestimo_tbl_status1`
    FOREIGN KEY (`FK_idStatus`)
    REFERENCES `mydb`.`tbl_status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
